// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package netty.codec;

public final class MessagePOJO {
    private MessagePOJO() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface MyQueryOrBuilder extends
            // @@protoc_insertion_point(interface_extends:MyQuery)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated int32 stuID = 1;</code>
         */
        java.util.List<java.lang.Integer> getStuIDList();
        /**
         * <code>repeated int32 stuID = 1;</code>
         */
        int getStuIDCount();
        /**
         * <code>repeated int32 stuID = 1;</code>
         */
        int getStuID(int index);
    }
    /**
     * Protobuf type {@code MyQuery}
     */
    public  static final class MyQuery extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:MyQuery)
            MyQueryOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use MyQuery.newBuilder() to construct.
        private MyQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private MyQuery() {
            stuID_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private MyQuery(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                stuID_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            stuID_.add(input.readInt32());
                            break;
                        }
                        case 10: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                                stuID_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                stuID_.add(input.readInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    stuID_ = java.util.Collections.unmodifiableList(stuID_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return netty.codec.MessagePOJO.internal_static_MyQuery_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return netty.codec.MessagePOJO.internal_static_MyQuery_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            netty.codec.MessagePOJO.MyQuery.class, netty.codec.MessagePOJO.MyQuery.Builder.class);
        }

        public static final int STUID_FIELD_NUMBER = 1;
        private java.util.List<java.lang.Integer> stuID_;
        /**
         * <code>repeated int32 stuID = 1;</code>
         */
        public java.util.List<java.lang.Integer>
        getStuIDList() {
            return stuID_;
        }
        /**
         * <code>repeated int32 stuID = 1;</code>
         */
        public int getStuIDCount() {
            return stuID_.size();
        }
        /**
         * <code>repeated int32 stuID = 1;</code>
         */
        public int getStuID(int index) {
            return stuID_.get(index);
        }
        private int stuIDMemoizedSerializedSize = -1;

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (getStuIDList().size() > 0) {
                output.writeUInt32NoTag(10);
                output.writeUInt32NoTag(stuIDMemoizedSerializedSize);
            }
            for (int i = 0; i < stuID_.size(); i++) {
                output.writeInt32NoTag(stuID_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < stuID_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(stuID_.get(i));
                }
                size += dataSize;
                if (!getStuIDList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                stuIDMemoizedSerializedSize = dataSize;
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof netty.codec.MessagePOJO.MyQuery)) {
                return super.equals(obj);
            }
            netty.codec.MessagePOJO.MyQuery other = (netty.codec.MessagePOJO.MyQuery) obj;

            boolean result = true;
            result = result && getStuIDList()
                    .equals(other.getStuIDList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getStuIDCount() > 0) {
                hash = (37 * hash) + STUID_FIELD_NUMBER;
                hash = (53 * hash) + getStuIDList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyQuery parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyQuery parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyQuery parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(netty.codec.MessagePOJO.MyQuery prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code MyQuery}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:MyQuery)
                netty.codec.MessagePOJO.MyQueryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return netty.codec.MessagePOJO.internal_static_MyQuery_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return netty.codec.MessagePOJO.internal_static_MyQuery_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                netty.codec.MessagePOJO.MyQuery.class, netty.codec.MessagePOJO.MyQuery.Builder.class);
            }

            // Construct using netty.codec.MessagePOJO.MyQuery.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                stuID_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return netty.codec.MessagePOJO.internal_static_MyQuery_descriptor;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyQuery getDefaultInstanceForType() {
                return netty.codec.MessagePOJO.MyQuery.getDefaultInstance();
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyQuery build() {
                netty.codec.MessagePOJO.MyQuery result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyQuery buildPartial() {
                netty.codec.MessagePOJO.MyQuery result = new netty.codec.MessagePOJO.MyQuery(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    stuID_ = java.util.Collections.unmodifiableList(stuID_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.stuID_ = stuID_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof netty.codec.MessagePOJO.MyQuery) {
                    return mergeFrom((netty.codec.MessagePOJO.MyQuery)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(netty.codec.MessagePOJO.MyQuery other) {
                if (other == netty.codec.MessagePOJO.MyQuery.getDefaultInstance()) return this;
                if (!other.stuID_.isEmpty()) {
                    if (stuID_.isEmpty()) {
                        stuID_ = other.stuID_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureStuIDIsMutable();
                        stuID_.addAll(other.stuID_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                netty.codec.MessagePOJO.MyQuery parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (netty.codec.MessagePOJO.MyQuery) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<java.lang.Integer> stuID_ = java.util.Collections.emptyList();
            private void ensureStuIDIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    stuID_ = new java.util.ArrayList<java.lang.Integer>(stuID_);
                    bitField0_ |= 0x00000001;
                }
            }
            /**
             * <code>repeated int32 stuID = 1;</code>
             */
            public java.util.List<java.lang.Integer>
            getStuIDList() {
                return java.util.Collections.unmodifiableList(stuID_);
            }
            /**
             * <code>repeated int32 stuID = 1;</code>
             */
            public int getStuIDCount() {
                return stuID_.size();
            }
            /**
             * <code>repeated int32 stuID = 1;</code>
             */
            public int getStuID(int index) {
                return stuID_.get(index);
            }
            /**
             * <code>repeated int32 stuID = 1;</code>
             */
            public Builder setStuID(
                    int index, int value) {
                ensureStuIDIsMutable();
                stuID_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated int32 stuID = 1;</code>
             */
            public Builder addStuID(int value) {
                ensureStuIDIsMutable();
                stuID_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated int32 stuID = 1;</code>
             */
            public Builder addAllStuID(
                    java.lang.Iterable<? extends java.lang.Integer> values) {
                ensureStuIDIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, stuID_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated int32 stuID = 1;</code>
             */
            public Builder clearStuID() {
                stuID_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:MyQuery)
        }

        // @@protoc_insertion_point(class_scope:MyQuery)
        private static final netty.codec.MessagePOJO.MyQuery DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new netty.codec.MessagePOJO.MyQuery();
        }

        public static netty.codec.MessagePOJO.MyQuery getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<MyQuery>
                PARSER = new com.google.protobuf.AbstractParser<MyQuery>() {
            @java.lang.Override
            public MyQuery parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MyQuery(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MyQuery> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MyQuery> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public netty.codec.MessagePOJO.MyQuery getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface MyReplyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:MyReply)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .Student stus = 1;</code>
         */
        java.util.List<netty.codec.MessagePOJO.Student>
        getStusList();
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        netty.codec.MessagePOJO.Student getStus(int index);
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        int getStusCount();
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        java.util.List<? extends netty.codec.MessagePOJO.StudentOrBuilder>
        getStusOrBuilderList();
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        netty.codec.MessagePOJO.StudentOrBuilder getStusOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code MyReply}
     */
    public  static final class MyReply extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:MyReply)
            MyReplyOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use MyReply.newBuilder() to construct.
        private MyReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private MyReply() {
            stus_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private MyReply(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                stus_ = new java.util.ArrayList<netty.codec.MessagePOJO.Student>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            stus_.add(
                                    input.readMessage(netty.codec.MessagePOJO.Student.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    stus_ = java.util.Collections.unmodifiableList(stus_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return netty.codec.MessagePOJO.internal_static_MyReply_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return netty.codec.MessagePOJO.internal_static_MyReply_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            netty.codec.MessagePOJO.MyReply.class, netty.codec.MessagePOJO.MyReply.Builder.class);
        }

        public static final int STUS_FIELD_NUMBER = 1;
        private java.util.List<netty.codec.MessagePOJO.Student> stus_;
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        public java.util.List<netty.codec.MessagePOJO.Student> getStusList() {
            return stus_;
        }
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        public java.util.List<? extends netty.codec.MessagePOJO.StudentOrBuilder>
        getStusOrBuilderList() {
            return stus_;
        }
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        public int getStusCount() {
            return stus_.size();
        }
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        public netty.codec.MessagePOJO.Student getStus(int index) {
            return stus_.get(index);
        }
        /**
         * <code>repeated .Student stus = 1;</code>
         */
        public netty.codec.MessagePOJO.StudentOrBuilder getStusOrBuilder(
                int index) {
            return stus_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < stus_.size(); i++) {
                output.writeMessage(1, stus_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < stus_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, stus_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof netty.codec.MessagePOJO.MyReply)) {
                return super.equals(obj);
            }
            netty.codec.MessagePOJO.MyReply other = (netty.codec.MessagePOJO.MyReply) obj;

            boolean result = true;
            result = result && getStusList()
                    .equals(other.getStusList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getStusCount() > 0) {
                hash = (37 * hash) + STUS_FIELD_NUMBER;
                hash = (53 * hash) + getStusList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static netty.codec.MessagePOJO.MyReply parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyReply parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyReply parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyReply parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(netty.codec.MessagePOJO.MyReply prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code MyReply}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:MyReply)
                netty.codec.MessagePOJO.MyReplyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return netty.codec.MessagePOJO.internal_static_MyReply_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return netty.codec.MessagePOJO.internal_static_MyReply_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                netty.codec.MessagePOJO.MyReply.class, netty.codec.MessagePOJO.MyReply.Builder.class);
            }

            // Construct using netty.codec.MessagePOJO.MyReply.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getStusFieldBuilder();
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (stusBuilder_ == null) {
                    stus_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    stusBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return netty.codec.MessagePOJO.internal_static_MyReply_descriptor;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyReply getDefaultInstanceForType() {
                return netty.codec.MessagePOJO.MyReply.getDefaultInstance();
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyReply build() {
                netty.codec.MessagePOJO.MyReply result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyReply buildPartial() {
                netty.codec.MessagePOJO.MyReply result = new netty.codec.MessagePOJO.MyReply(this);
                int from_bitField0_ = bitField0_;
                if (stusBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        stus_ = java.util.Collections.unmodifiableList(stus_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.stus_ = stus_;
                } else {
                    result.stus_ = stusBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof netty.codec.MessagePOJO.MyReply) {
                    return mergeFrom((netty.codec.MessagePOJO.MyReply)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(netty.codec.MessagePOJO.MyReply other) {
                if (other == netty.codec.MessagePOJO.MyReply.getDefaultInstance()) return this;
                if (stusBuilder_ == null) {
                    if (!other.stus_.isEmpty()) {
                        if (stus_.isEmpty()) {
                            stus_ = other.stus_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureStusIsMutable();
                            stus_.addAll(other.stus_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.stus_.isEmpty()) {
                        if (stusBuilder_.isEmpty()) {
                            stusBuilder_.dispose();
                            stusBuilder_ = null;
                            stus_ = other.stus_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            stusBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getStusFieldBuilder() : null;
                        } else {
                            stusBuilder_.addAllMessages(other.stus_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                netty.codec.MessagePOJO.MyReply parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (netty.codec.MessagePOJO.MyReply) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<netty.codec.MessagePOJO.Student> stus_ =
                    java.util.Collections.emptyList();
            private void ensureStusIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    stus_ = new java.util.ArrayList<netty.codec.MessagePOJO.Student>(stus_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    netty.codec.MessagePOJO.Student, netty.codec.MessagePOJO.Student.Builder, netty.codec.MessagePOJO.StudentOrBuilder> stusBuilder_;

            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public java.util.List<netty.codec.MessagePOJO.Student> getStusList() {
                if (stusBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(stus_);
                } else {
                    return stusBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public int getStusCount() {
                if (stusBuilder_ == null) {
                    return stus_.size();
                } else {
                    return stusBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public netty.codec.MessagePOJO.Student getStus(int index) {
                if (stusBuilder_ == null) {
                    return stus_.get(index);
                } else {
                    return stusBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder setStus(
                    int index, netty.codec.MessagePOJO.Student value) {
                if (stusBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStusIsMutable();
                    stus_.set(index, value);
                    onChanged();
                } else {
                    stusBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder setStus(
                    int index, netty.codec.MessagePOJO.Student.Builder builderForValue) {
                if (stusBuilder_ == null) {
                    ensureStusIsMutable();
                    stus_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    stusBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder addStus(netty.codec.MessagePOJO.Student value) {
                if (stusBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStusIsMutable();
                    stus_.add(value);
                    onChanged();
                } else {
                    stusBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder addStus(
                    int index, netty.codec.MessagePOJO.Student value) {
                if (stusBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStusIsMutable();
                    stus_.add(index, value);
                    onChanged();
                } else {
                    stusBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder addStus(
                    netty.codec.MessagePOJO.Student.Builder builderForValue) {
                if (stusBuilder_ == null) {
                    ensureStusIsMutable();
                    stus_.add(builderForValue.build());
                    onChanged();
                } else {
                    stusBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder addStus(
                    int index, netty.codec.MessagePOJO.Student.Builder builderForValue) {
                if (stusBuilder_ == null) {
                    ensureStusIsMutable();
                    stus_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    stusBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder addAllStus(
                    java.lang.Iterable<? extends netty.codec.MessagePOJO.Student> values) {
                if (stusBuilder_ == null) {
                    ensureStusIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, stus_);
                    onChanged();
                } else {
                    stusBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder clearStus() {
                if (stusBuilder_ == null) {
                    stus_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    stusBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public Builder removeStus(int index) {
                if (stusBuilder_ == null) {
                    ensureStusIsMutable();
                    stus_.remove(index);
                    onChanged();
                } else {
                    stusBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public netty.codec.MessagePOJO.Student.Builder getStusBuilder(
                    int index) {
                return getStusFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public netty.codec.MessagePOJO.StudentOrBuilder getStusOrBuilder(
                    int index) {
                if (stusBuilder_ == null) {
                    return stus_.get(index);  } else {
                    return stusBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public java.util.List<? extends netty.codec.MessagePOJO.StudentOrBuilder>
            getStusOrBuilderList() {
                if (stusBuilder_ != null) {
                    return stusBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(stus_);
                }
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public netty.codec.MessagePOJO.Student.Builder addStusBuilder() {
                return getStusFieldBuilder().addBuilder(
                        netty.codec.MessagePOJO.Student.getDefaultInstance());
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public netty.codec.MessagePOJO.Student.Builder addStusBuilder(
                    int index) {
                return getStusFieldBuilder().addBuilder(
                        index, netty.codec.MessagePOJO.Student.getDefaultInstance());
            }
            /**
             * <code>repeated .Student stus = 1;</code>
             */
            public java.util.List<netty.codec.MessagePOJO.Student.Builder>
            getStusBuilderList() {
                return getStusFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    netty.codec.MessagePOJO.Student, netty.codec.MessagePOJO.Student.Builder, netty.codec.MessagePOJO.StudentOrBuilder>
            getStusFieldBuilder() {
                if (stusBuilder_ == null) {
                    stusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            netty.codec.MessagePOJO.Student, netty.codec.MessagePOJO.Student.Builder, netty.codec.MessagePOJO.StudentOrBuilder>(
                            stus_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    stus_ = null;
                }
                return stusBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:MyReply)
        }

        // @@protoc_insertion_point(class_scope:MyReply)
        private static final netty.codec.MessagePOJO.MyReply DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new netty.codec.MessagePOJO.MyReply();
        }

        public static netty.codec.MessagePOJO.MyReply getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<MyReply>
                PARSER = new com.google.protobuf.AbstractParser<MyReply>() {
            @java.lang.Override
            public MyReply parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MyReply(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MyReply> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MyReply> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public netty.codec.MessagePOJO.MyReply getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface StudentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Student)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>string name = 2;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>int32 score = 3;</code>
         */
        int getScore();
    }
    /**
     * Protobuf type {@code Student}
     */
    public  static final class Student extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Student)
            StudentOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Student.newBuilder() to construct.
        private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Student() {
            id_ = 0;
            name_ = "";
            score_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Student(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 24: {

                            score_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return netty.codec.MessagePOJO.internal_static_Student_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return netty.codec.MessagePOJO.internal_static_Student_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            netty.codec.MessagePOJO.Student.class, netty.codec.MessagePOJO.Student.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private int id_;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SCORE_FIELD_NUMBER = 3;
        private int score_;
        /**
         * <code>int32 score = 3;</code>
         */
        public int getScore() {
            return score_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (score_ != 0) {
                output.writeInt32(3, score_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (score_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, score_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof netty.codec.MessagePOJO.Student)) {
                return super.equals(obj);
            }
            netty.codec.MessagePOJO.Student other = (netty.codec.MessagePOJO.Student) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getName()
                    .equals(other.getName());
            result = result && (getScore()
                    == other.getScore());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + SCORE_FIELD_NUMBER;
            hash = (53 * hash) + getScore();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static netty.codec.MessagePOJO.Student parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Student parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(netty.codec.MessagePOJO.Student prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Student}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Student)
                netty.codec.MessagePOJO.StudentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return netty.codec.MessagePOJO.internal_static_Student_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return netty.codec.MessagePOJO.internal_static_Student_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                netty.codec.MessagePOJO.Student.class, netty.codec.MessagePOJO.Student.Builder.class);
            }

            // Construct using netty.codec.MessagePOJO.Student.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;

                name_ = "";

                score_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return netty.codec.MessagePOJO.internal_static_Student_descriptor;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Student getDefaultInstanceForType() {
                return netty.codec.MessagePOJO.Student.getDefaultInstance();
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Student build() {
                netty.codec.MessagePOJO.Student result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Student buildPartial() {
                netty.codec.MessagePOJO.Student result = new netty.codec.MessagePOJO.Student(this);
                result.id_ = id_;
                result.name_ = name_;
                result.score_ = score_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof netty.codec.MessagePOJO.Student) {
                    return mergeFrom((netty.codec.MessagePOJO.Student)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(netty.codec.MessagePOJO.Student other) {
                if (other == netty.codec.MessagePOJO.Student.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getScore() != 0) {
                    setScore(other.getScore());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                netty.codec.MessagePOJO.Student parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (netty.codec.MessagePOJO.Student) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int id_ ;
            /**
             * <code>int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";
            /**
             * <code>string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private int score_ ;
            /**
             * <code>int32 score = 3;</code>
             */
            public int getScore() {
                return score_;
            }
            /**
             * <code>int32 score = 3;</code>
             */
            public Builder setScore(int value) {

                score_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 score = 3;</code>
             */
            public Builder clearScore() {

                score_ = 0;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Student)
        }

        // @@protoc_insertion_point(class_scope:Student)
        private static final netty.codec.MessagePOJO.Student DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new netty.codec.MessagePOJO.Student();
        }

        public static netty.codec.MessagePOJO.Student getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Student>
                PARSER = new com.google.protobuf.AbstractParser<Student>() {
            @java.lang.Override
            public Student parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Student(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Student> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Student> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public netty.codec.MessagePOJO.Student getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_MyQuery_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_MyQuery_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_MyReply_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_MyReply_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Student_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Student_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rMessage.proto\"\030\n\007MyQuery\022\r\n\005stuID\030\001 \003(" +
                        "\005\"!\n\007MyReply\022\026\n\004stus\030\001 \003(\0132\010.Student\"2\n\007" +
                        "Student\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005sco" +
                        "re\030\003 \001(\005B\032\n\013netty.codecB\013MessagePOJOb\006pr" +
                        "oto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_MyQuery_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_MyQuery_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_MyQuery_descriptor,
                new java.lang.String[] { "StuID", });
        internal_static_MyReply_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_MyReply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_MyReply_descriptor,
                new java.lang.String[] { "Stus", });
        internal_static_Student_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Student_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Student_descriptor,
                new java.lang.String[] { "Id", "Name", "Score", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
