// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package netty.codec;

public final class MessagePOJO {
    private MessagePOJO() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    /**
     * Protobuf enum {@code DataType}
     */
    public enum DataType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>StudentType = 0;</code>
         */
        StudentType(0),
        /**
         * <code>TeacherType = 1;</code>
         */
        TeacherType(1),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>StudentType = 0;</code>
         */
        public static final int StudentType_VALUE = 0;
        /**
         * <code>TeacherType = 1;</code>
         */
        public static final int TeacherType_VALUE = 1;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static DataType valueOf(int value) {
            return forNumber(value);
        }

        public static DataType forNumber(int value) {
            switch (value) {
                case 0: return StudentType;
                case 1: return TeacherType;
                default: return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
            return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
                DataType> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
                    public DataType findValueByNumber(int number) {
                        return DataType.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return netty.codec.MessagePOJO.getDescriptor().getEnumTypes().get(0);
        }

        private static final DataType[] VALUES = values();

        public static DataType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private DataType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:DataType)
    }

    public interface MyMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:MyMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.DataType data_type = 1;</code>
         */
        int getDataTypeValue();
        /**
         * <code>.DataType data_type = 1;</code>
         */
        netty.codec.MessagePOJO.DataType getDataType();

        /**
         * <code>.Student student = 2;</code>
         */
        boolean hasStudent();
        /**
         * <code>.Student student = 2;</code>
         */
        netty.codec.MessagePOJO.Student getStudent();
        /**
         * <code>.Student student = 2;</code>
         */
        netty.codec.MessagePOJO.StudentOrBuilder getStudentOrBuilder();

        /**
         * <code>.Teacher teacher = 3;</code>
         */
        boolean hasTeacher();
        /**
         * <code>.Teacher teacher = 3;</code>
         */
        netty.codec.MessagePOJO.Teacher getTeacher();
        /**
         * <code>.Teacher teacher = 3;</code>
         */
        netty.codec.MessagePOJO.TeacherOrBuilder getTeacherOrBuilder();

        public netty.codec.MessagePOJO.MyMessage.DataBodyCase getDataBodyCase();
    }
    /**
     * Protobuf type {@code MyMessage}
     */
    public  static final class MyMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:MyMessage)
            MyMessageOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use MyMessage.newBuilder() to construct.
        private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private MyMessage() {
            dataType_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private MyMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            int rawValue = input.readEnum();

                            dataType_ = rawValue;
                            break;
                        }
                        case 18: {
                            netty.codec.MessagePOJO.Student.Builder subBuilder = null;
                            if (dataBodyCase_ == 2) {
                                subBuilder = ((netty.codec.MessagePOJO.Student) dataBody_).toBuilder();
                            }
                            dataBody_ =
                                    input.readMessage(netty.codec.MessagePOJO.Student.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom((netty.codec.MessagePOJO.Student) dataBody_);
                                dataBody_ = subBuilder.buildPartial();
                            }
                            dataBodyCase_ = 2;
                            break;
                        }
                        case 26: {
                            netty.codec.MessagePOJO.Teacher.Builder subBuilder = null;
                            if (dataBodyCase_ == 3) {
                                subBuilder = ((netty.codec.MessagePOJO.Teacher) dataBody_).toBuilder();
                            }
                            dataBody_ =
                                    input.readMessage(netty.codec.MessagePOJO.Teacher.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom((netty.codec.MessagePOJO.Teacher) dataBody_);
                                dataBody_ = subBuilder.buildPartial();
                            }
                            dataBodyCase_ = 3;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return netty.codec.MessagePOJO.internal_static_MyMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return netty.codec.MessagePOJO.internal_static_MyMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            netty.codec.MessagePOJO.MyMessage.class, netty.codec.MessagePOJO.MyMessage.Builder.class);
        }

        private int dataBodyCase_ = 0;
        private java.lang.Object dataBody_;
        public enum DataBodyCase
                implements com.google.protobuf.Internal.EnumLite {
            STUDENT(2),
            TEACHER(3),
            DATABODY_NOT_SET(0);
            private final int value;
            private DataBodyCase(int value) {
                this.value = value;
            }
            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static DataBodyCase valueOf(int value) {
                return forNumber(value);
            }

            public static DataBodyCase forNumber(int value) {
                switch (value) {
                    case 2: return STUDENT;
                    case 3: return TEACHER;
                    case 0: return DATABODY_NOT_SET;
                    default: return null;
                }
            }
            public int getNumber() {
                return this.value;
            }
        };

        public DataBodyCase
        getDataBodyCase() {
            return DataBodyCase.forNumber(
                    dataBodyCase_);
        }

        public static final int DATA_TYPE_FIELD_NUMBER = 1;
        private int dataType_;
        /**
         * <code>.DataType data_type = 1;</code>
         */
        public int getDataTypeValue() {
            return dataType_;
        }
        /**
         * <code>.DataType data_type = 1;</code>
         */
        public netty.codec.MessagePOJO.DataType getDataType() {
            @SuppressWarnings("deprecation")
            netty.codec.MessagePOJO.DataType result = netty.codec.MessagePOJO.DataType.valueOf(dataType_);
            return result == null ? netty.codec.MessagePOJO.DataType.UNRECOGNIZED : result;
        }

        public static final int STUDENT_FIELD_NUMBER = 2;
        /**
         * <code>.Student student = 2;</code>
         */
        public boolean hasStudent() {
            return dataBodyCase_ == 2;
        }
        /**
         * <code>.Student student = 2;</code>
         */
        public netty.codec.MessagePOJO.Student getStudent() {
            if (dataBodyCase_ == 2) {
                return (netty.codec.MessagePOJO.Student) dataBody_;
            }
            return netty.codec.MessagePOJO.Student.getDefaultInstance();
        }
        /**
         * <code>.Student student = 2;</code>
         */
        public netty.codec.MessagePOJO.StudentOrBuilder getStudentOrBuilder() {
            if (dataBodyCase_ == 2) {
                return (netty.codec.MessagePOJO.Student) dataBody_;
            }
            return netty.codec.MessagePOJO.Student.getDefaultInstance();
        }

        public static final int TEACHER_FIELD_NUMBER = 3;
        /**
         * <code>.Teacher teacher = 3;</code>
         */
        public boolean hasTeacher() {
            return dataBodyCase_ == 3;
        }
        /**
         * <code>.Teacher teacher = 3;</code>
         */
        public netty.codec.MessagePOJO.Teacher getTeacher() {
            if (dataBodyCase_ == 3) {
                return (netty.codec.MessagePOJO.Teacher) dataBody_;
            }
            return netty.codec.MessagePOJO.Teacher.getDefaultInstance();
        }
        /**
         * <code>.Teacher teacher = 3;</code>
         */
        public netty.codec.MessagePOJO.TeacherOrBuilder getTeacherOrBuilder() {
            if (dataBodyCase_ == 3) {
                return (netty.codec.MessagePOJO.Teacher) dataBody_;
            }
            return netty.codec.MessagePOJO.Teacher.getDefaultInstance();
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (dataType_ != netty.codec.MessagePOJO.DataType.StudentType.getNumber()) {
                output.writeEnum(1, dataType_);
            }
            if (dataBodyCase_ == 2) {
                output.writeMessage(2, (netty.codec.MessagePOJO.Student) dataBody_);
            }
            if (dataBodyCase_ == 3) {
                output.writeMessage(3, (netty.codec.MessagePOJO.Teacher) dataBody_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (dataType_ != netty.codec.MessagePOJO.DataType.StudentType.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, dataType_);
            }
            if (dataBodyCase_ == 2) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, (netty.codec.MessagePOJO.Student) dataBody_);
            }
            if (dataBodyCase_ == 3) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, (netty.codec.MessagePOJO.Teacher) dataBody_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof netty.codec.MessagePOJO.MyMessage)) {
                return super.equals(obj);
            }
            netty.codec.MessagePOJO.MyMessage other = (netty.codec.MessagePOJO.MyMessage) obj;

            boolean result = true;
            result = result && dataType_ == other.dataType_;
            result = result && getDataBodyCase().equals(
                    other.getDataBodyCase());
            if (!result) return false;
            switch (dataBodyCase_) {
                case 2:
                    result = result && getStudent()
                            .equals(other.getStudent());
                    break;
                case 3:
                    result = result && getTeacher()
                            .equals(other.getTeacher());
                    break;
                case 0:
                default:
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
            hash = (53 * hash) + dataType_;
            switch (dataBodyCase_) {
                case 2:
                    hash = (37 * hash) + STUDENT_FIELD_NUMBER;
                    hash = (53 * hash) + getStudent().hashCode();
                    break;
                case 3:
                    hash = (37 * hash) + TEACHER_FIELD_NUMBER;
                    hash = (53 * hash) + getTeacher().hashCode();
                    break;
                case 0:
                default:
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.MyMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(netty.codec.MessagePOJO.MyMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code MyMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:MyMessage)
                netty.codec.MessagePOJO.MyMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return netty.codec.MessagePOJO.internal_static_MyMessage_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return netty.codec.MessagePOJO.internal_static_MyMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                netty.codec.MessagePOJO.MyMessage.class, netty.codec.MessagePOJO.MyMessage.Builder.class);
            }

            // Construct using netty.codec.MessagePOJO.MyMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                dataType_ = 0;

                dataBodyCase_ = 0;
                dataBody_ = null;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return netty.codec.MessagePOJO.internal_static_MyMessage_descriptor;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyMessage getDefaultInstanceForType() {
                return netty.codec.MessagePOJO.MyMessage.getDefaultInstance();
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyMessage build() {
                netty.codec.MessagePOJO.MyMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.MyMessage buildPartial() {
                netty.codec.MessagePOJO.MyMessage result = new netty.codec.MessagePOJO.MyMessage(this);
                result.dataType_ = dataType_;
                if (dataBodyCase_ == 2) {
                    if (studentBuilder_ == null) {
                        result.dataBody_ = dataBody_;
                    } else {
                        result.dataBody_ = studentBuilder_.build();
                    }
                }
                if (dataBodyCase_ == 3) {
                    if (teacherBuilder_ == null) {
                        result.dataBody_ = dataBody_;
                    } else {
                        result.dataBody_ = teacherBuilder_.build();
                    }
                }
                result.dataBodyCase_ = dataBodyCase_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof netty.codec.MessagePOJO.MyMessage) {
                    return mergeFrom((netty.codec.MessagePOJO.MyMessage)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(netty.codec.MessagePOJO.MyMessage other) {
                if (other == netty.codec.MessagePOJO.MyMessage.getDefaultInstance()) return this;
                if (other.dataType_ != 0) {
                    setDataTypeValue(other.getDataTypeValue());
                }
                switch (other.getDataBodyCase()) {
                    case STUDENT: {
                        mergeStudent(other.getStudent());
                        break;
                    }
                    case TEACHER: {
                        mergeTeacher(other.getTeacher());
                        break;
                    }
                    case DATABODY_NOT_SET: {
                        break;
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                netty.codec.MessagePOJO.MyMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (netty.codec.MessagePOJO.MyMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int dataBodyCase_ = 0;
            private java.lang.Object dataBody_;
            public DataBodyCase
            getDataBodyCase() {
                return DataBodyCase.forNumber(
                        dataBodyCase_);
            }

            public Builder clearDataBody() {
                dataBodyCase_ = 0;
                dataBody_ = null;
                onChanged();
                return this;
            }


            private int dataType_ = 0;
            /**
             * <code>.DataType data_type = 1;</code>
             */
            public int getDataTypeValue() {
                return dataType_;
            }
            /**
             * <code>.DataType data_type = 1;</code>
             */
            public Builder setDataTypeValue(int value) {
                dataType_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>.DataType data_type = 1;</code>
             */
            public netty.codec.MessagePOJO.DataType getDataType() {
                @SuppressWarnings("deprecation")
                netty.codec.MessagePOJO.DataType result = netty.codec.MessagePOJO.DataType.valueOf(dataType_);
                return result == null ? netty.codec.MessagePOJO.DataType.UNRECOGNIZED : result;
            }
            /**
             * <code>.DataType data_type = 1;</code>
             */
            public Builder setDataType(netty.codec.MessagePOJO.DataType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                dataType_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>.DataType data_type = 1;</code>
             */
            public Builder clearDataType() {

                dataType_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.SingleFieldBuilderV3<
                    netty.codec.MessagePOJO.Student, netty.codec.MessagePOJO.Student.Builder, netty.codec.MessagePOJO.StudentOrBuilder> studentBuilder_;
            /**
             * <code>.Student student = 2;</code>
             */
            public boolean hasStudent() {
                return dataBodyCase_ == 2;
            }
            /**
             * <code>.Student student = 2;</code>
             */
            public netty.codec.MessagePOJO.Student getStudent() {
                if (studentBuilder_ == null) {
                    if (dataBodyCase_ == 2) {
                        return (netty.codec.MessagePOJO.Student) dataBody_;
                    }
                    return netty.codec.MessagePOJO.Student.getDefaultInstance();
                } else {
                    if (dataBodyCase_ == 2) {
                        return studentBuilder_.getMessage();
                    }
                    return netty.codec.MessagePOJO.Student.getDefaultInstance();
                }
            }
            /**
             * <code>.Student student = 2;</code>
             */
            public Builder setStudent(netty.codec.MessagePOJO.Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    dataBody_ = value;
                    onChanged();
                } else {
                    studentBuilder_.setMessage(value);
                }
                dataBodyCase_ = 2;
                return this;
            }
            /**
             * <code>.Student student = 2;</code>
             */
            public Builder setStudent(
                    netty.codec.MessagePOJO.Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    dataBody_ = builderForValue.build();
                    onChanged();
                } else {
                    studentBuilder_.setMessage(builderForValue.build());
                }
                dataBodyCase_ = 2;
                return this;
            }
            /**
             * <code>.Student student = 2;</code>
             */
            public Builder mergeStudent(netty.codec.MessagePOJO.Student value) {
                if (studentBuilder_ == null) {
                    if (dataBodyCase_ == 2 &&
                            dataBody_ != netty.codec.MessagePOJO.Student.getDefaultInstance()) {
                        dataBody_ = netty.codec.MessagePOJO.Student.newBuilder((netty.codec.MessagePOJO.Student) dataBody_)
                                .mergeFrom(value).buildPartial();
                    } else {
                        dataBody_ = value;
                    }
                    onChanged();
                } else {
                    if (dataBodyCase_ == 2) {
                        studentBuilder_.mergeFrom(value);
                    }
                    studentBuilder_.setMessage(value);
                }
                dataBodyCase_ = 2;
                return this;
            }
            /**
             * <code>.Student student = 2;</code>
             */
            public Builder clearStudent() {
                if (studentBuilder_ == null) {
                    if (dataBodyCase_ == 2) {
                        dataBodyCase_ = 0;
                        dataBody_ = null;
                        onChanged();
                    }
                } else {
                    if (dataBodyCase_ == 2) {
                        dataBodyCase_ = 0;
                        dataBody_ = null;
                    }
                    studentBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>.Student student = 2;</code>
             */
            public netty.codec.MessagePOJO.Student.Builder getStudentBuilder() {
                return getStudentFieldBuilder().getBuilder();
            }
            /**
             * <code>.Student student = 2;</code>
             */
            public netty.codec.MessagePOJO.StudentOrBuilder getStudentOrBuilder() {
                if ((dataBodyCase_ == 2) && (studentBuilder_ != null)) {
                    return studentBuilder_.getMessageOrBuilder();
                } else {
                    if (dataBodyCase_ == 2) {
                        return (netty.codec.MessagePOJO.Student) dataBody_;
                    }
                    return netty.codec.MessagePOJO.Student.getDefaultInstance();
                }
            }
            /**
             * <code>.Student student = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    netty.codec.MessagePOJO.Student, netty.codec.MessagePOJO.Student.Builder, netty.codec.MessagePOJO.StudentOrBuilder>
            getStudentFieldBuilder() {
                if (studentBuilder_ == null) {
                    if (!(dataBodyCase_ == 2)) {
                        dataBody_ = netty.codec.MessagePOJO.Student.getDefaultInstance();
                    }
                    studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            netty.codec.MessagePOJO.Student, netty.codec.MessagePOJO.Student.Builder, netty.codec.MessagePOJO.StudentOrBuilder>(
                            (netty.codec.MessagePOJO.Student) dataBody_,
                            getParentForChildren(),
                            isClean());
                    dataBody_ = null;
                }
                dataBodyCase_ = 2;
                onChanged();;
                return studentBuilder_;
            }

            private com.google.protobuf.SingleFieldBuilderV3<
                    netty.codec.MessagePOJO.Teacher, netty.codec.MessagePOJO.Teacher.Builder, netty.codec.MessagePOJO.TeacherOrBuilder> teacherBuilder_;
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public boolean hasTeacher() {
                return dataBodyCase_ == 3;
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public netty.codec.MessagePOJO.Teacher getTeacher() {
                if (teacherBuilder_ == null) {
                    if (dataBodyCase_ == 3) {
                        return (netty.codec.MessagePOJO.Teacher) dataBody_;
                    }
                    return netty.codec.MessagePOJO.Teacher.getDefaultInstance();
                } else {
                    if (dataBodyCase_ == 3) {
                        return teacherBuilder_.getMessage();
                    }
                    return netty.codec.MessagePOJO.Teacher.getDefaultInstance();
                }
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public Builder setTeacher(netty.codec.MessagePOJO.Teacher value) {
                if (teacherBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    dataBody_ = value;
                    onChanged();
                } else {
                    teacherBuilder_.setMessage(value);
                }
                dataBodyCase_ = 3;
                return this;
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public Builder setTeacher(
                    netty.codec.MessagePOJO.Teacher.Builder builderForValue) {
                if (teacherBuilder_ == null) {
                    dataBody_ = builderForValue.build();
                    onChanged();
                } else {
                    teacherBuilder_.setMessage(builderForValue.build());
                }
                dataBodyCase_ = 3;
                return this;
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public Builder mergeTeacher(netty.codec.MessagePOJO.Teacher value) {
                if (teacherBuilder_ == null) {
                    if (dataBodyCase_ == 3 &&
                            dataBody_ != netty.codec.MessagePOJO.Teacher.getDefaultInstance()) {
                        dataBody_ = netty.codec.MessagePOJO.Teacher.newBuilder((netty.codec.MessagePOJO.Teacher) dataBody_)
                                .mergeFrom(value).buildPartial();
                    } else {
                        dataBody_ = value;
                    }
                    onChanged();
                } else {
                    if (dataBodyCase_ == 3) {
                        teacherBuilder_.mergeFrom(value);
                    }
                    teacherBuilder_.setMessage(value);
                }
                dataBodyCase_ = 3;
                return this;
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public Builder clearTeacher() {
                if (teacherBuilder_ == null) {
                    if (dataBodyCase_ == 3) {
                        dataBodyCase_ = 0;
                        dataBody_ = null;
                        onChanged();
                    }
                } else {
                    if (dataBodyCase_ == 3) {
                        dataBodyCase_ = 0;
                        dataBody_ = null;
                    }
                    teacherBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public netty.codec.MessagePOJO.Teacher.Builder getTeacherBuilder() {
                return getTeacherFieldBuilder().getBuilder();
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            public netty.codec.MessagePOJO.TeacherOrBuilder getTeacherOrBuilder() {
                if ((dataBodyCase_ == 3) && (teacherBuilder_ != null)) {
                    return teacherBuilder_.getMessageOrBuilder();
                } else {
                    if (dataBodyCase_ == 3) {
                        return (netty.codec.MessagePOJO.Teacher) dataBody_;
                    }
                    return netty.codec.MessagePOJO.Teacher.getDefaultInstance();
                }
            }
            /**
             * <code>.Teacher teacher = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    netty.codec.MessagePOJO.Teacher, netty.codec.MessagePOJO.Teacher.Builder, netty.codec.MessagePOJO.TeacherOrBuilder>
            getTeacherFieldBuilder() {
                if (teacherBuilder_ == null) {
                    if (!(dataBodyCase_ == 3)) {
                        dataBody_ = netty.codec.MessagePOJO.Teacher.getDefaultInstance();
                    }
                    teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            netty.codec.MessagePOJO.Teacher, netty.codec.MessagePOJO.Teacher.Builder, netty.codec.MessagePOJO.TeacherOrBuilder>(
                            (netty.codec.MessagePOJO.Teacher) dataBody_,
                            getParentForChildren(),
                            isClean());
                    dataBody_ = null;
                }
                dataBodyCase_ = 3;
                onChanged();;
                return teacherBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:MyMessage)
        }

        // @@protoc_insertion_point(class_scope:MyMessage)
        private static final netty.codec.MessagePOJO.MyMessage DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new netty.codec.MessagePOJO.MyMessage();
        }

        public static netty.codec.MessagePOJO.MyMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<MyMessage>
                PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
            @java.lang.Override
            public MyMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MyMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MyMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MyMessage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public netty.codec.MessagePOJO.MyMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface StudentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Student)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>string name = 2;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();
    }
    /**
     * Protobuf type {@code Student}
     */
    public  static final class Student extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Student)
            StudentOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Student.newBuilder() to construct.
        private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Student() {
            id_ = 0;
            name_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Student(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return netty.codec.MessagePOJO.internal_static_Student_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return netty.codec.MessagePOJO.internal_static_Student_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            netty.codec.MessagePOJO.Student.class, netty.codec.MessagePOJO.Student.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private int id_;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof netty.codec.MessagePOJO.Student)) {
                return super.equals(obj);
            }
            netty.codec.MessagePOJO.Student other = (netty.codec.MessagePOJO.Student) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getName()
                    .equals(other.getName());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static netty.codec.MessagePOJO.Student parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Student parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Student parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(netty.codec.MessagePOJO.Student prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Student}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Student)
                netty.codec.MessagePOJO.StudentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return netty.codec.MessagePOJO.internal_static_Student_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return netty.codec.MessagePOJO.internal_static_Student_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                netty.codec.MessagePOJO.Student.class, netty.codec.MessagePOJO.Student.Builder.class);
            }

            // Construct using netty.codec.MessagePOJO.Student.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;

                name_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return netty.codec.MessagePOJO.internal_static_Student_descriptor;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Student getDefaultInstanceForType() {
                return netty.codec.MessagePOJO.Student.getDefaultInstance();
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Student build() {
                netty.codec.MessagePOJO.Student result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Student buildPartial() {
                netty.codec.MessagePOJO.Student result = new netty.codec.MessagePOJO.Student(this);
                result.id_ = id_;
                result.name_ = name_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof netty.codec.MessagePOJO.Student) {
                    return mergeFrom((netty.codec.MessagePOJO.Student)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(netty.codec.MessagePOJO.Student other) {
                if (other == netty.codec.MessagePOJO.Student.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                netty.codec.MessagePOJO.Student parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (netty.codec.MessagePOJO.Student) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int id_ ;
            /**
             * <code>int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";
            /**
             * <code>string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Student)
        }

        // @@protoc_insertion_point(class_scope:Student)
        private static final netty.codec.MessagePOJO.Student DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new netty.codec.MessagePOJO.Student();
        }

        public static netty.codec.MessagePOJO.Student getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Student>
                PARSER = new com.google.protobuf.AbstractParser<Student>() {
            @java.lang.Override
            public Student parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Student(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Student> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Student> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public netty.codec.MessagePOJO.Student getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface TeacherOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Teacher)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 age = 1;</code>
         */
        int getAge();

        /**
         * <code>string name = 2;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public  static final class Teacher extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Teacher)
            TeacherOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Teacher.newBuilder() to construct.
        private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Teacher() {
            age_ = 0;
            name_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Teacher(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            age_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return netty.codec.MessagePOJO.internal_static_Teacher_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return netty.codec.MessagePOJO.internal_static_Teacher_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            netty.codec.MessagePOJO.Teacher.class, netty.codec.MessagePOJO.Teacher.Builder.class);
        }

        public static final int AGE_FIELD_NUMBER = 1;
        private int age_;
        /**
         * <code>int32 age = 1;</code>
         */
        public int getAge() {
            return age_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (age_ != 0) {
                output.writeInt32(1, age_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, age_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof netty.codec.MessagePOJO.Teacher)) {
                return super.equals(obj);
            }
            netty.codec.MessagePOJO.Teacher other = (netty.codec.MessagePOJO.Teacher) obj;

            boolean result = true;
            result = result && (getAge()
                    == other.getAge());
            result = result && getName()
                    .equals(other.getName());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static netty.codec.MessagePOJO.Teacher parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Teacher parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Teacher parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static netty.codec.MessagePOJO.Teacher parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(netty.codec.MessagePOJO.Teacher prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Teacher}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Teacher)
                netty.codec.MessagePOJO.TeacherOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return netty.codec.MessagePOJO.internal_static_Teacher_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return netty.codec.MessagePOJO.internal_static_Teacher_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                netty.codec.MessagePOJO.Teacher.class, netty.codec.MessagePOJO.Teacher.Builder.class);
            }

            // Construct using netty.codec.MessagePOJO.Teacher.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                age_ = 0;

                name_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return netty.codec.MessagePOJO.internal_static_Teacher_descriptor;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Teacher getDefaultInstanceForType() {
                return netty.codec.MessagePOJO.Teacher.getDefaultInstance();
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Teacher build() {
                netty.codec.MessagePOJO.Teacher result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public netty.codec.MessagePOJO.Teacher buildPartial() {
                netty.codec.MessagePOJO.Teacher result = new netty.codec.MessagePOJO.Teacher(this);
                result.age_ = age_;
                result.name_ = name_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof netty.codec.MessagePOJO.Teacher) {
                    return mergeFrom((netty.codec.MessagePOJO.Teacher)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(netty.codec.MessagePOJO.Teacher other) {
                if (other == netty.codec.MessagePOJO.Teacher.getDefaultInstance()) return this;
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                netty.codec.MessagePOJO.Teacher parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (netty.codec.MessagePOJO.Teacher) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int age_ ;
            /**
             * <code>int32 age = 1;</code>
             */
            public int getAge() {
                return age_;
            }
            /**
             * <code>int32 age = 1;</code>
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 age = 1;</code>
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";
            /**
             * <code>string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Teacher)
        }

        // @@protoc_insertion_point(class_scope:Teacher)
        private static final netty.codec.MessagePOJO.Teacher DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new netty.codec.MessagePOJO.Teacher();
        }

        public static netty.codec.MessagePOJO.Teacher getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Teacher>
                PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
            @java.lang.Override
            public Teacher parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Teacher(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Teacher> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Teacher> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public netty.codec.MessagePOJO.Teacher getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_MyMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_MyMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Student_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Student_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Teacher_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Teacher_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rMessage.proto\"o\n\tMyMessage\022\034\n\tdata_typ" +
                        "e\030\001 \001(\0162\t.DataType\022\033\n\007student\030\002 \001(\0132\010.St" +
                        "udentH\000\022\033\n\007teacher\030\003 \001(\0132\010.TeacherH\000B\n\n\010" +
                        "dataBody\"#\n\007Student\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030" +
                        "\002 \001(\t\"$\n\007Teacher\022\013\n\003age\030\001 \001(\005\022\014\n\004name\030\002 " +
                        "\001(\t*,\n\010DataType\022\017\n\013StudentType\020\000\022\017\n\013Teac" +
                        "herType\020\001B\032\n\013netty.codecB\013MessagePOJOb\006p" +
                        "roto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_MyMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_MyMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_MyMessage_descriptor,
                new java.lang.String[] { "DataType", "Student", "Teacher", "DataBody", });
        internal_static_Student_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Student_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Student_descriptor,
                new java.lang.String[] { "Id", "Name", });
        internal_static_Teacher_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Teacher_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Teacher_descriptor,
                new java.lang.String[] { "Age", "Name", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
